services:
  frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: frontend_c
        ports:
            - '5173:5173'
        volumes:
            - './client:/app'
            - /app/node_modules
        depends_on:
            backend:
                condition: service_started
  backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend_c
        ports:
            - '5174:5174'
        volumes:
            - './backend:/app'
            - /app/node_modules
        depends_on:
            mariadb:
                condition: service_started
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mariadb-data:
